#ifndef LDISPLEDCONFIG_H
#define LDISPLEDCONFIG_H

#define LDISP_ROWS 5
#define LDISP_COLS 22
#define LDISP_NOF_LEDS (LDISP_ROWS * LDISP_COLS)
#define LDISP_LED_DATA_SIZE 4
#define LDISP_FRAME_SIZE (LDISP_NOF_LEDS * LDISP_LED_DATA_SIZE)


#endif // LDISPLEDCONFIG_H
